# baseURL = "https://demo.gethugothemes.com/navigator/"
baseURL = "http://localhost:2020/"
languageCode = "en-us"
title = "Navigator | Responsive Multipurpose Bootstrap Hugo Template"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Gestion des langues : FR / EN / NL / DE
[[Params.listeLangues]]
code = "en"

# meta data
author = "Themefisher"
description = "This is meta description"


############# 2 - Site en ENGLISH
[Languages.en]
weight = 2
languageCode = "en-us"
title = "Chartered Professional Accountants"
dateFormat = "January 2, 2006"
home = "Home"
logo = "images/logo2.png"
menufixed = true

footerDescription = "Richard Liu & Company, Inc. is a well-established Chartered Professional Accounting firm located in Vancouver, BC."
footerServiceTitle = "Service"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "About"
footerSubscribeTitle = "Subscribe"


# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "Richard Liu & Company"
description = "Richard Liu & Company, Inc. is a well-established Chartered Professional Accounting firm located in Vancouver, BC. We provide a wide range of accounting, tax and compliance services, as well as business management and advisory to owner-managed businesses, professional corporations and individuals."
button  = false
btnText = "Know More"
btnURL  = "https://themefisher.com/"
videoThumb = "images/slider/home-top-sm.jpg"
videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "What makes us unique from other CPA firms?"
description = "Our experience encompasses a broad spectrum of industries, including real estate, construction, retailers, restaurants, importers/exporters, professionals, manufacturers and other owner-managed businesses."

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = false
topTitle= "OUR UNTOLD STORY"
title   = "Blog."
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.en.params.contact]
enable  = true
topTitle= "DROP US A NOTE"
title   = "Contact Us."
subtitle = "To request a free consultation, simply contact us!"
officehoursTitle = "Office Hours"
officehours = "9:00 a.m. to 5:00 p.m. Monday to Friday.<br>Available after hours and on weekends by appointment."
address = "550 West Broadway, Suite 525 <br> Vancouver, BC, Canada <br> V5Z 0E9"
phone   = "604.638.9991"
fax     = "604.325.7557"
email   = "info@richardliucga.com"
facebook= "https://www.facebook.com/"
twitter = "https://twitter.com/"
linkedin= "https://www.linkedin.com/"
dribbble= "https://dribbble.com/"
instagram= "https://www.instagram.com/"
mapLatitude = "49.2632022"
mapLongitude= "-123.1166529"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Let's Create Something Together"
subtitle= ""
btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "about"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "service"
url     = "service"
weight  = 3
# [[menu.nav]]
# name    = "portfolio"
# url     = "portfolio"
# weight  = 4
# [[menu.nav]]
# name    = "blog"
# url     = "blog"
# weight  = 5
[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 6
[[menu.nav]]
name    = "中文"
url     = "service_cn"
weight  = 7

# Footer Service Menu
[[menu.service]]
name    = "graphicdesign"
url     = "service"
weight  = 1
[[menu.service]]
name    = "webdesign"
url     = "service"
weight  = 2
[[menu.service]]
name    = "webdevelopment"
url     = "service"
weight  = 3

# Footer Quick links Menu
[[menu.quicklink]]
name    = "about"
url     = "about"
weight  = 1
[[menu.quicklink]]
name    = "contact"
url     = "contact"
weight  = 2
[[menu.quicklink]]
name    = "service"
url     = "service"
weight  = 3

